.TH CRAN "1" "January 2022" "Cran" "General Commands Manual"


.SH NAME

cran \- an easy package manager for R written in bash


.SH SYNOPSIS

.B cran
[\fI\,OPTION\/\fR] [\fI\,VALUES\/\fR]


.SH DESCRIPTION

.TP
\fBversion\fR, \fBv\fR, \fB\-v\fR, \fBver\fR
Print version and exit

.TP
\fBinstall\fR, \fBi\fR, \fB\-i\fR, \fBint\fR
Install package(s)

.TP
\fBdownload\fR, \fBd\fR, \fB\-d\fR, \fBdow\fR
Download package(s) source

.TP
\fBremove\fR, \fBr\fR, \fB\-r\fR, \fBrm\fR
Remove/uninstall package(s)

.TP
\fBlist\fR, \fBl\fR, \fB\-l\fR, \fBls\fR
List installed packages

.TP
\fBhelp\fR, \fBh\fR, \fB\-h\fR, \fBhlp\fR
Print all commands

.TP
\fBupdate\fR, \fBu\fR, \fB\-u\fR, \fBupt\fR
Update all packages

.TP
\fBupdates\fR, \fBU\fR, \fB\-U\fR, \fBupd\fR
Print all updatable packages

.TP
\fBdepends\fR, \fBD\fR, \fB\-D\fR, \fBdep\fR
Print dependencies in cranfile

.SH "CONFIG FILE"

By default the config file is in
.IR ~/.config/cran.conf .
It get created automatically on first launch.

Configuration variables are:

.TP
\fBrepos\fR
This is an R vector of your mirrors seperated by spaces (
.IR "https://mirror1.com https://mirror2.com ..."
), this will get translated into an R vector

.TP
\fBroot_required\fR
This value controls if cran requires root access to run

.TP
\fBr_interpreter\fR
The path to your R interpreter

.TP
\fBr_flags\fR
The flags passed to the R interpreter when running a command, I'd suggest leaving it as-is


.SH EXAMPLES

.TP
cran version
Output cran version


.SH AUTHOR

Written by Ari Archer <ari@mail.ari-web.xyz>


.SH "REPORTING BUGS"

Report any bugs or feature requests to https://ari-web.xyz/gh/cran issues

