.TH CRAN "1" "January 2022" "Cran" "User commands"


.SH NAME

cran \-  an easy package manager for R written in bash


.SH SYNOPSIS

.B cran
[\fI\,OPTION\/\fR] [\fI\,VALUES\/\fR]


.SH DESCRIPTION

.TP
\fBversion\fR, \fBv\fR, \fB\-v\fR, \fBver\fR
Print version and exit

.TP
\fBinstall\fR, \fBi\fR, \fB\-i\fR, \fBint\fR
Install package(s)

.TP
\fBdownload\fR, \fBd\fR, \fB\-d\fR, \fBdow\fR
Download package(s) source

.TP
\fBremove\fR, \fBr\fR, \fB\-r\fR, \fBrm\fR
Remove/uninstall package(s)

.TP
\fBlist\fR, \fBl\fR, \fB\-l\fR, \fBls\fR
List installed packages

.TP
\fBhelp\fR, \fBh\fR, \fB\-h\fR, \fBhlp\fR
Print all commands

.TP
\fBupdate\fR, \fBu\fR, \fB\-u\fR, \fBupt\fR
Update all packages

.TP
\fBupdates\fR, \fBU\fR, \fB\-U\fR, \fBupd\fR
Print all updatable packages

.TP
\fBdepends\fR, \fBD\fR, \fB\-D\fR, \fBdep\fR
Print dependencies in cranfile


.SH EXAMPLES

.TP
cran version
Output cran version


.SH AUTHOR

Written by Ari Archer <ari@mail.ari-web.xyz>


.SH "REPORTING BUGS"

Report any bugs or feature requests to https://ari-web.xyz/gh/cran issues

